- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 10HRS
    TRAINER: ABHI
  tasks:
  - name: print course details
    ansible.builtin.debug:
    #Vars reference should be surronded by ""
      msg: "Hello {{ COURSE }} , Course Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"