- name: variables from files
  hosts: local
  connection: local
  vars_files: #https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#defining-variables-in-included-files-and-roles
  - course.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello i am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"