- name: understand preference
  hosts: local
  connection: local
  vars:
  GREETING: "Hello frOm play"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: please enter gretting.
    private: false
  tasks:
  - name: print the greeting.
    vars:
    GREETING: "Hello from task"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"

