- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debian:
      msg: "Hello, {{ item }}" #item is reserverd keyword
    loop:
    - suresh
    - ramesh
    - joseph
    - raheem